image: python:latest

before_script:
  - pip install -r requirements.txt

stages:
  - check

lint:
  stage: check
  script:
    - flake8

test:
  stage: check
  script: 
    - cd src && python -m pytest

